### PR TITLE
Refund Email

### PR DESCRIPTION
**Pull request by ryancarlson**
Update incorrect wording in emails sent to users who are given a refund.  The wording actually makes it sound like they have given a new payment.

I did quite a bit of restructuring the logic in this commit too.  It can be split out in a separate commit if the reviewer requests it.

### CODE REVIEW

**Comment by ryancarlson** [comment]
@wrandall22 can you look at this one too please?

**Comment by ryancarlson** [comment]
fixed the whitespace... was there anything else?

**Comment by wrandall22** [comment]
Looks good to me.

**Comment by ryancarlson** [comment]
Thanks!

On Thu, Jan 22, 2015 at 3:21 PM, wrandall22 <notifications@github.com>
wrote:

> Looks good to me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CruGlobal/conf-registration-api/pull/341#issuecomment-71091355>
> .
>



-- 
*Ryan Carlson*
Application Development Team
ryan.t.carlson@cru.org

**Pull request merged**
