### PR TITLE
Preserve completed timestamp

### PR DESCRIPTION
**Pull request by ryancarlson**
When updating a completed registration, don't lose the completed timestamp

 - it only happened when adding a registrant to a completed registration, but it was possible to lose the completed timestamp
 - this change will look at the registration pulled from the database, if it already has a completed timestamp, then it will be preserved

### CODE REVIEW

**Comment by ryancarlson** [comment]
@mattfred can you review this real quick please?

**Comment by mattfred** [comment]
LGTM

**Comment by ryancarlson** [comment]
Thanks

**Comment by ryancarlson** [comment]
Thanks

**Pull request merged**
