### PR TITLE
Add conference search abilities

### PR DESCRIPTION
**Pull request by ryancarlson**
- created an endpoint to search for conference
- added a service to do the database queries
- added some tests for the above items
- renamed a couple `ConferenceService` methods that have bugged me for a long time now.

### CODE REVIEW

**Comment by ryancarlson** [comment]
@wrandall22 sorry to load you up, but here's another one that would be great if you could review for me?

**Comment by ryancarlson** [comment]
@wrandall22 did you have any other feedback on this PR?

**Comment by wrandall22** [comment]
Nope, looks good to me.

**Comment by ryancarlson** [comment]
Thanks!

**Pull request merged**
