### PR TITLE
Event 171 - performance enhancements for large conferences/events

### PR DESCRIPTION
**Pull request by ryancarlson**
- when retrieving all registrations/registrants on a conference, by default no answers are returned
    - for large events (> 200 registrants) it was taking upwards of 30 seconds to do full table scans of the answers table for each registrant
- so that the web client's data views still look correct, name and email of the registrant are now stored on the registrants table.
   - since answers aren't retrieved, a lot of blank rows were showing up
- for all existing registrants, name and email were moved from answers to registrants via a java migration
- `CrsUserService` no longer updates the session expiration timestamp
   - since all updates and selects happen in one large transaction, it would lock the identities table for the duration of the request.  that request could be > 30 sec, so yeah that's bad
   - a filter is now applied to update the session timestamp after the completion of a successful request.  this happens in its own transaction now.
- since answers are not returned when fetching all registrations for a conference, the data export now has to be generated in a separate call server side.  this call looks up all the answers for all registrations and returns a download file in csv format.
   - there is one endpoint for registrations and one for payments

### CODE REVIEW

**Comment by ryancarlson** [comment]
@mattfred or @mattdrees kind of a large one here... can you review sometime tomorrow?  (I may do a fixup and squash some commits... I can do that first if you prefer)

**Comment by mattdrees** [comment]
it's too big of a change for me to be able to review (given my other tasks). @mattfred can you do the review?

**Comment by mattfred** [comment]
Yes I will take care of it.

**Comment by ryancarlson** [comment]
Actually hold off on this for the moment... i want to clean it up and add some more tests.

**Pull request closed without merging**
